<div class="article">

    <div class="article-title">
        <h2>
            <a href="<?php echo $this->broker('url')->direct(array(
                'action' => 'view',
                'controller' => 'news',
                'slug' => $this->vars('news')->slug
            ), 'news', true); ?>"><?php echo $this->vars()->escape($this->vars('news')->title); ?></a>
        </h2>
    </div>

    <div class="article-content">
        <?php echo $this->vars('news')->text; ?>
    </div>

    <div class="article-footer-outer">
        <div class="article-footer">
            <span>
                <a href="<?php echo $this->broker('url')->direct(array(
                    'action' => 'browse',
                    'controller' => 'news',
                    'category' => $this->vars('news')->category_slug
                ), 'category', true); ?>"><?php echo $this->vars('news')->category_title; ?></a>
            </span>

            <span>
                <a href="#comments">
                    <?php //echo $this->numberOfComments($this->vars('news')->id); ?>
                </a>
            </span>

            <span>
                <a href="<?php echo $this->broker('url')->direct(array(
                    'action' => 'browse',
                    'controller' => 'news',
                    'date' => date('Y-m-d', strtotime($this->vars('news')->datetime_added))
                        ), 'date', true); ?>">
                    <?php echo date('d.m.Y.', strtotime($this->vars('news')->datetime_added)); ?>
                </a>
            </span>
        </div>
    </div>

    <div class="article-tags">
        Oznake: <?php //echo $this->tags($this->vars('news')->id); ?>
    </div>

</div>

<div id="comments">

    <?php //$comments = $this->comments($this->vars('news')->id); ?>

    <?php /*if(count($comments) > 0): ?>

        <?php foreach($comments as $comment): ?>
        <div class="comments">
            <span>
                <?php echo $this->vars()->escape($comment->name); ?>
            </span>
            <span>
                <?php echo $this->vars()->escape($comment->datetime_added); ?>
            </span>
            <div>
                <?php echo $this->vars()->escape($comment->comment); ?>
            </div>
        </div>
        <?php endforeach; ?>

    <?php else: ?>
    <div class="comments">
        Nema komentara.
    </div>
    <?php endif; ?>

    <div class="comments">
    <?php echo $this->flashMessenger(); ?>
    </div>
<?php */ ?>
    <?php echo $this->vars('commentsForm'); ?>
</div>